source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'selenium-webdriver'
gem 'capybara'
gem 'site_prism'
gem 'rest-client'
gem 'json'
#gem 'page-object', '~> 2.0'
#gem 'data_magic'
